[package]
name = "async_reverse_proxy"
version = "0.1.0"
authors = ["Casey Allred <sbditto85@gmail.com>"]

[dependencies]
env_logger = "0.5.9"
bytes = "0.4.7"
actix = "0.5.6"
actix-web = {version="0.5.6",features=["alpn"]}
futures = "0.1.21"
http = "0.1.5"
